#security:
#  oauth2:
#    client:
#      clientId: bd1c0a783ccdd1c9b9e4
#      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#      clientAuthenticationScheme: form

server:
  jetty:
    accesslog:
      enabled: true
      logServer: true
      logLatency: true
      extended-format: true
  port: 8080
management:
  server:
    port: 9080